# Generated by Django 3.2 on 2023-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230622_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
