# Generated by Django 3.2 on 2023-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230622_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='role',
        ),
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loanstatus',
            field=models.CharField(choices=[('reject', 'reject'), ('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
